spring.application.name=gatewayService
server.port=9000
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.server.webflux.routes[0].id=CouponModule
spring.cloud.gateway.server.webflux.routes[0].uri=lb://COUPON-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/coupon/**


spring.cloud.gateway.server.webflux.routes[1].id=IcecreamModule
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ICECREAM
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/ice/**
